### ISSUE TITLE
precision problem of Lab and CMYK color space 

### ISSUE THREAD

**Issue by huangbuyi** [gka/chroma.js#126]
Lab color space
```
chroma.lab(80, 40, 130).rgb();  // [255,165,0]
chroma.rgb(255, 165, 0).lab();  // [74.94,23.93,78.95]
```

CMYK color space
```
chroma.cmyk(0.01, 1, 1, 0.01).rgb();  // [250,0,0]
chroma.rgb(250,0,0).cmyk();  // [0,1,1,0.02]
```

`Math.round()` parsed other color space to RGB integer, have a great influence on parsed back. Hence, I want to remove `round()` method from code, is it a good idea to solve the precision problem?

**Comment by gka** [comment]
huh, good point. I still want to keep the rounding on RGB output, but you're right, the internal _rgb should be floats for higher precision

**Comment by gka** [comment]
regarding your first example, while there is still the rounding problem, it is not as dramatic as you think. the reason the numbers are off is that some RGB colors have multiple representations in Lab.

if I take the `[74.94,23.93,78.95]` as input I get something pretty close to it
```
chroma.rgb(chroma.lab(74.94, 23.93, 78.95).rgb()).lab()
[ 74.93565017306031, 23.933170767745093, 78.94977540341804 ]
```

the same can happen with CMYK too. `[0.2, 0.2, 0.2, 0]` and `[0, 0, 0, 0.2]` are both the same gray in RGB.

(the issue is still valid)

**Comment by gka** [comment]
so indeed the two cmyk colors in your exampe are identical in RGB space
```
chroma.cmyk(0.01, 1, 1, 0.01).hex() // '#fa0000'
chroma.cmyk(0, 1, 1, 0.02).hex() // '#fa0000'
```
even with the precise RGB channels preserved, there is no way of knowing which of the two CMYK colors is the "right" one.

```js
chroma.cmyk(0.01, 1, 1, 0.01).rgb(false)  // [ 249.9255, 0, 0 ]
chroma.cmyk(0, 1, 1, 0.02).rgb(false)  // [ 249.9, 0, 0 ]

**Comment by gka** [comment]
added high precision internal rgb storage to version 1.3.0

**Comment by huangbuyi** [comment]
thanks for your work
