### ISSUE TITLE
Implement simple comparison operatos

### ISSUE THREAD

**Issue by oakkitten** [gka/chroma.js#196]
Currently `chroma(1) == chroma(1)` returns `false`

Also, why is `chroma('blue').darken(-3)` pink? is there a way to get a brighter blue that is still blue with this library?

**Comment by gka** [comment]
Chroma returns a new object instance every time you construct a new color, and the JavaScript `==` operator only returns true if the object references are pointing to the same instance. If you want to compare if two colors are equal you could just compare a string representation, like `chroma(1).hex() == chroma(1).hex()`.

The other question is a little trickier. First, to explain the problem, `.darken()` and `.brighten()` are using the Lch color space to make colors lighter and darker. This works quite well for many colors, like 
`#004381` as shown in this [depiction of the Lch color space with a constant hue of 247](http://tristen.ca/hcl-picker/#/clh/6/247/004381/F7EDFA):

![image](https://user-images.githubusercontent.com/617518/47786376-e61f7480-dd0b-11e8-93a3-74c742bb47f4.png)

However, the "true" RGB blue `#0000ff`, or similar highly saturated blues, are found in Lch space in the [almost purple hue of 268](http://tristen.ca/hcl-picker/#/clh/6/268/051EA3/FBE5CF). Therefore, increasing the Lch lightness will lead to a light purple tone instead of a light blue.

![image](https://user-images.githubusercontent.com/617518/47786356-d56efe80-dd0b-11e8-8318-4f0afb51fc02.png)

One way around this would be to mix your color with white in RGB space. But there is a similar problem with the color `#0000ff` here. Mixing it with 80% white results in `#ccccff` which is not exactly a light blue but more of a light purple.

In chroma you can do this via 

```
chroma.mix('blue', 'white', 0.8);  // #ccccff
```
