### ISSUE TITLE
How to get the percent of color

### ISSUE THREAD

**Issue by owant** [gka/chroma.js#212]
```
scale = chroma.scale(['white', 'red']);
scale(0.5).hex(); // #FF7F7F
```
from the simple code,I want to get some color in the linearcolor percent(positon);like this
```
scale("white").percent();//return 1
```
How should I get this function?

**Comment by Artoria2e5** [comment]
shouldn't your example return 0 instead?

I don't think this would be a good idea (gka might have a different opinion) because scales are not necessarily monotonic and bijective: it is totally fine to have two spots that hit the same color. Solving for a point on a weird mathemetical function is something you would ask for a magicalOldTonEquationSolver to do, not for a color library.

For example you can use https://github.com/scijs/newton-raphson-method:

```JS
function findWhereMaybe(sample, scale) {
  let nr = require('newton-raphson-method')
  // rgb distance might be faster and good enough for "same thing”
  let howFar = (x) => (chroma.distance(scale(x), sample, 'rgb'))
  let dom = scale.domain()
  return nr(howFar, dom[0] + dom[dom.length -1]) / 2, { tolerance: 2 }) // start with the midpoint
}
```
