### ISSUE TITLE
How to get closest 'name' to a chroma value?

### ISSUE THREAD

**Issue by davidjgonzalez** [gka/chroma.js#248]
I am deriving colors from an image, and I would like to get the closed "named" color (in the event that the exact color does not have a 'named`' color, and only returns the hex value). 

Is this possible via an API call? And/or is there a way to easily do this (ex. would i have to get the color, and add 1 to r/g/b until that resolves to a `name`? and then decrement - and pick the closer of the two)

**Comment by meodai** [comment]
@davidjgonzalez there is no method that does that. Because there are X ways to determine what color is closest to another. However I made a library: https://github.com/meodai/ClosestVector that I am using to do exactly this. The demo page has an example with colors: https://meodai.github.io/ClosestVector/ (https://github.com/meodai/ClosestVector/blob/master/index.html#L372)

**Comment by davidjgonzalez** [comment]
@meodai  Thanks!
I was actually just about to come back and post a followup as I finished up my day: I ended up finding this module: https://www.npmjs.com/package/color-namer that works pretty well, it has a number of color lists (basic, roygbiv, pantone, etc.) so you can get a pretty interesting granularity of colors (though I think most ppl have no idea what some of them are :))

**Comment by meodai** [comment]
@davidjgonzalez I am the maintainer of "color-names" so of course I am biased :D

**Comment by davidjgonzalez** [comment]
@meodai ooh! i clicked through and it looks nice! ill take a closer look - and i just might have to switch over... !
