### ISSUE TITLE
readme.md lies about zero-dependency

### ISSUE THREAD

**Issue by josch** [gka/chroma.js#283]
The readme states "Chroma.js is a tiny small-ish zero-dependency JavaScript library". This is not true as in `package.json` it lists a dependency:

```
  "dependencies": {
    "cross-env": "^6.0.3"
  }
```

Please remove the dependency or change the readme as appropriate. Thanks!

**Comment by lcb931023** [comment]
`cross-env` is a dependency that makes it easier to build `chroma.js`. It's not a dependency of the library itself :)

You can read more about [cross-env here](https://www.npmjs.com/package/cross-env)

**Comment by josch** [comment]
> It's not a dependency of the library itself :)

Yes it is. Read the `package.json`. Yes, this is probably a bug and the dependency should probably move to `devDependencies` but it isn't yet. So as of right now, due to this bug, chroma-js is *not* zero-dependency. Right now, everybody who installs (not builds) chroma-js will also need to install cross-env.

**Comment by lcb931023** [comment]
I see what you meant. I’ve been using the minified file directly so zero-dependency just meant to me that the inner working of the library doesn’t rely on any other pieces of code, and it pulling cross-env when installed through a version manager wasn’t a problem for me. 

Since the developer is taking a break from maintaining this library as noted in Readme, pull requests are unlikely to go through. I would recommend maintaining a fork of this lib, and pulling that through your choice of package managers :)

**Comment by gka** [comment]
`cross-env` has been moved to devDependencies, so chroma.js again is zero-dependencies :)
