### ISSUE TITLE
rollup-plugin-terser has been deprecated

### ISSUE THREAD

**Issue by MasaruKitajima** [gka/chroma.js#324]
According to [npm](https://www.npmjs.com/), `rollup-plugin-terser` has been deprecated.

On the page, it says;

> This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

Please confirm it, and if possible, please check versions of dependcies.

**Comment by regorxxx** [comment]
See this:
https://github.com/gka/chroma.js/issues/321

**Comment by MasaruKitajima** [comment]
Thank you so much.
My apologies for being late.
I'll try it.

**Comment by MasaruKitajima** [comment]
I cloned your repo and ran "npm insatall," but it failed.
I tried to install under Node v18.14.0, v18.17.0, and v20.11.0.
Which version of Node.js is required?
[18.14.0.log](https://github.com/gka/chroma.js/files/14174346/18.14.0.log)
[18.17.0.log](https://github.com/gka/chroma.js/files/14174347/18.17.0.log)
[20.11.0.log](https://github.com/gka/chroma.js/files/14174348/20.11.0.log)

**Comment by regorxxx** [comment]
You are supposed to delete the package-lock.json file before building, obviously. Also, you don't need to build it yourself, it's already built on the repo (?)

Have tested it today with v20.11.0. and zero problems anyway.

**Comment by MasaruKitajima** [comment]
@regorxxx 
Thank you for answering to me.
I deleted the package-lock.json file before building, but still got errors.
I suppose they're my own problems because I use [anyenv](https://github.com/anyenv/anyenv) and [nodenv](https://github.com/nodenv/nodenv) on my Mac.

May I ask you what do you mean by the following?

> t's already built on the repo 

I visited your repo and went to the release page, I found source code only.
My intention is to have a interactive web on localhost.

Blessings!

**Comment by regorxxx** [comment]
I mean you don't need to build the source code to get working files for web, since it's already built and offered with every update.

Those files are ready to use.
https://github.com/regorxxx/chroma.js/blob/main/chroma.js
https://github.com/regorxxx/chroma.js/blob/main/chroma.min.js

(if you read the docs there, you will see different flavors are offered)

> I deleted the package-lock.json file before building, but still got errors.
To be honest, npm building is sometimes a pain... if you write here the new errors maybe we can find where the problem lies. Today I found a problem on windows only, but it worked fine on unix and Mac.
Nothing has changed about building compared to the old fork though (I even fixed a few errors).

**Comment by gka** [comment]
thanks for raising the issue. this will get fixed once #336 is merged.
