### ISSUE TITLE
npm ERR! code ERESOLVE occurs on `npm install`

### ISSUE THREAD

**Issue by MasaruKitajima** [gka/chroma.js#335]
My node version is `v20.12.2` and npm version is `10.5.2`

When I ran `npm install`, I got error as followings.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: chroma-js@2.4.2
npm ERR! Found: rollup@4.18.0
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^4.18.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^2.0.0" from rollup-plugin-terser@7.0.2
npm ERR! node_modules/rollup-plugin-terser
npm ERR!   dev rollup-plugin-terser@"^7.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

How can I fix these erros?

**Comment by gka** [comment]
I think the imports will be fixed once https://github.com/gka/chroma.js/pull/336 is merged

**Comment by MasaruKitajima** [comment]
Thank you so much. I'll try it later and will report.

**Comment by gka** [comment]
Should be fixed in 2.5.0 now, just tested it with Node v20.11.1

**Comment by clhenrick** [comment]
@gka not sure if it relates to this issue but I'm seeing "invalid module" when `require`'ing `chroma-js` on ObservableHQ. This was working fine yesterday. I see a dependabot PR was recently merged 2 hours ago, perhaps that broke something?

Example notebook: https://observablehq.com/d/7a7e8b4d8fda8036

**Comment by gka** [comment]
@clhenrick hm, I think that's a problem with how ObservableHQ is importing npm modules when using its `require` method. Confusingly, this is not using Node's `require` but it's an alias for [d3-require](https://github.com/d3/d3-require) which doesn't seem to support the way chroma-js is bundled since 2.5.0.

However, you can import chroma.js using the newer `import` syntax:

```js
// works only in Observable Notebooks
chroma = (await import("https://unpkg.com/chroma-js")).default
```

Here's a demo notebook: https://observablehq.com/@gka/chroma-js 

Btw, you can also import `chroma` from this notebook directly

```js
// works only in Observable Notebooks
import {chroma} from "@gka/chroma-js"
```

Btw, importing chroma.js works fine in other places, e.g., this [Svelte REPL](https://svelte.dev/repl/c8f49036f6e54a8783ddcbd8eb28996a?version=4.2.18).

**Comment by gka** [comment]
@MasaruKitajima I tested importing chroma.js via npm both using `require` and `import` and it works fine, so I'll close this issue now. Thanks for reporting the bug.

**Comment by MasaruKitajima** [comment]
@gka Thank you for your efforts.
I could build it successfully.
Again, many thanks for your great efforts.
