### ISSUE TITLE
Black + .hsl return NaN for hue

### ISSUE THREAD

**Issue by KyleAMathews** [gka/chroma.js#64]
e.g.

```javascript
chroma('black').hsl()
--> (NaN, 0, 0)
```

**Comment by gka** [comment]
that's not a bug, that's a feature :)

seriously, black and white, and all gray values in between have no hue value.

**Comment by KyleAMathews** [comment]
This... seems more clever than useful :)

Is compatibility with browsers not the goal? They would say black is `hsl(0, 0%, 0%)`

**Comment by gka** [comment]
Unlike browsers, chroma.js does do color interpolation, and there are strange side effects when you automatically treat white/gray/black as zero saturated reds. 

Lets say you want to mix blue, say hsl(220, 80%, 60%), with black, hsl(0,0,0). It would be weird if the result would be a dark purple like hsl(290, 40%, 30%), right? blue mixed with black should be dark blue. 

one way to implement this is to store hue-less colors with a NaN as hue value. it is not wrong, since there is in fact no single hue angle. it is not the only way, but my argument is that this is the cleanest way. 

on the other hand, you're right about browser compatibility. if you explicitly format a color as css-ready hsl, it should fallback to "hsl(0,0,0)" rather than "hsl(NaN, 0,0)". 

i'll look into this.

thx

**Comment by KyleAMathews** [comment]
Cool, this makes sense. I just use `.css()` generally so it's not an active problem, just noticed it once while exploring.

**Comment by gka** [comment]
fixed in 0.7.5. thanks!
