### ISSUE TITLE
Convert between internal color modes

### ISSUE THREAD

**Issue by KyleAMathews** [gka/chroma.js#75]
Perhaps it was just an accident but previously I was writing code like `chroma('#eee', 'lab')` which would convert the internal color mode to lab.

This broke sometime after 0.7.2.

What is the recommended way to create a chroma object then convert between internal color modes?

**Comment by gka** [comment]
actually, there has never been an internal color mode, as internally, all colors are stored as RGB(A). 

instead of having an internal color mode, you can set the mode for operations where it makes sense, such as [chroma.mix](http://gka.github.io/chroma.js/#chroma-mix):

```js
chroma.mix('red', 'blue', 0.5, 'rgb');
chroma.mix('red', 'blue', 0.5, 'hsl');
chroma.mix('red', 'blue', 0.5, 'lab');
chroma.mix('red', 'blue', 0.5, 'lch');
```

another example would be `chroma.scale`, which allows you to set an internal mode using [scale.mode](http://gka.github.io/chroma.js/#scale-mode) which is then used to interpolate the colors.

```js
chroma.scale(['yellow', 'navy']);
chroma.scale(['yellow', 'navy']).mode('lab');
```

hope this answers your question

**Comment by KyleAMathews** [comment]
Oh interesting...

Can you set the mode when setting luminance? I'd like the new luminance to
be found in "lab" space not "rgb" space.

**Comment by gka** [comment]
There are two options.

You can either use [color.set](http://gka.github.io/chroma.js/#color-set) to set the *lightness* in [Lab](https://en.wikipedia.org/wiki/Lab_color_space), which is not the same as luminance, but probably similar for most use cases.

```js
chroma('skyblue').set('lab.l', 90);
```

The concept of relative luminance is something I took from [W3C WCAG](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef), and that is defined in RGB. To 'adjust' the luminance of the color it is interpolated with either white or black until the luminance is close enough. By default, this black/white interpolation is done in RGB but you can define the interpolation space in the second argument.

```js
chroma('skyblue').luminance(0.8, 'lab');
chroma('skyblue').luminance(0.8, 'hsl');
```

**Comment by gka** [comment]
closing
